FROM ubuntu:16.04

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y wget && apt-get install -y build-essential
WORKDIR /usr/local
RUN wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b -p /usr/local/conda

ENV PATH /usr/local/conda/bin

RUN conda config --set ssl_verify false && conda update -q -y conda


CMD ["python3", "-V"]