version: '3.7'

services:
  # MongoDB
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.0.5
    volumes:
      - type: volume
        source: my_db
        target: /data
        volume:
          nocopy: true
    ports:
      - '27017:27017'

  webapp:
    container_name: flask
    build:
      context: .
    volumes:
      - type: volume
        source: my_vol
        target: /usr/app/logs
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  my_vol:
  my_db:
