version: '3.7'

services:
  # MongoDB
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.0.5
    volumes:
      - my_db:/data
    ports:
      - '27017:27017'

  webapp:
    container_name: flask
    build:
      context: .
      target: deploy
    volumes:
      - my_vol:/usr/app/logs
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo

  webapp_test:
    container_name: test
    build:
      context: .
      target: test
    volumes:
      - my_vol:/usr/app/logs
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  my_vol:
  my_db:
